name: SRS Survey Backend CICD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: "Dockerfile"
          push: true
          tags: teqqiestech/srs-survey-backend:latest
      
      - name: Sending Build Update
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "[Github Actions] srs-survey-backend has been pushed to Docker.\nStarting deployment"
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - 
        name: multiple command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            sudo bash ./testScript/e2etest.sh
            sudo bash ./deployment/srs-survey-backend.sh
            
